# Generated by Django 3.0.2 on 2020-02-03 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HwPdf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='dumb', max_length=100)),
                ('pdf_file', models.FileField(upload_to='pdfs/')),
            ],
        ),
    ]
