# Generated by Django 3.0.2 on 2020-02-03 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hwpdf',
            name='image_file',
            field=models.FileField(null=True, upload_to='image_files/'),
        ),
    ]
