# Generated by Django 3.0.2 on 2020-02-03 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_hwpdf_image_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hwpdf',
            name='image_file',
            field=models.FileField(blank=True, null=True, upload_to='image_files/'),
        ),
        migrations.AlterField(
            model_name='hwpdf',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='pdfs/'),
        ),
    ]
