# Generated by Django 3.0.2 on 2020-02-06 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200203_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='hwpdf',
            name='content',
            field=models.TextField(default='', max_length=5000000000),
        ),
    ]
